import pygame
pygame.init()

#VENTANA
TAMANO_VENTANA = (1280, 720) #1280, 720
COLOR_VENTANA = (135, 255, 255)
RESOLUCION_VENTANA_ACTUAL = (0, 0)

#JUEGO
FPS = 60

#HUD
FUENTE = pygame.font.SysFont("Arial", 24, "bold")

#JUGADOR
ANCHO_JUGADOR = 251
ALTO_JUGADOR = 90
COLOR_JUGADOR = (26, 106, 23)

#ENEMIGO
ANCHO_ENEMIGO = 50
ALTO_ENEMIGO = 50
COLOR_ENEMIGO = (206, 8, 8)

#BALAS
ANCHO_BALA = 30
ALTO_BALA = 30
COLOR_BALA = (0, 0, 0)
TIEMPO_ENTRE_BALAS = 12
TIEMPO_RECARGA = 90
CANTIDAD_MUNICION = 20



#FUNCIONES
def establecer_resolucion(resolucion):
    global RESOLUCION_VENTANA_ACTUAL
    RESOLUCION_VENTANA_ACTUAL = resolucion



